export const words = [
	{
        verses: [
        "Cikini, Cikini, Cikini, Cikini",
        "Cikini ke Gondangdia",
        "Kujadi begini gara-gara dia",
        "Cikampek, Tasikmalaya",
        "Hatiku capek bila kau tak setia",
        "Jakarta ke Jayapura",
        "Jangan cinta kalau cuma pura-pura",
        "Madura sampai Papua",
        "Jangan kau kira ku tak bisa mendua",
        "Walau kau hanya tukang ojek",
        "Tak pernah absen meski hujan dan becek",
        "Walau kau hanya supir bajaj",
        "Hatiku senang tiap kali kau belai",
        "Percuma kau jadi pilot",
        "Makin tinggi cintamu makin melorot",
        "Apalagi kau jadi nahkoda",
        "Jarang pulang pernah kau kepincut janda",
        "Biarpun sederhana, asalkan kau setia",
        "Aku pun akan s'lalu cinta",
        "Percuma banyak harta, di luar kau mendua",
        "Jangan kira ku diam saja",
        "Cikini ke Gondangdia",
        "Ku begini gara-gara dia",
        "Cikampek, Tasikmalaya",
        "Hati capek bila kau tak setia",
        "Jakarta ke Jayapura",
        "Jangan cinta kalau pura-pura",
        "Madura sampai Papua",
        "Jangan kira ku tak bisa mendua",
        "Walau kau hanya tukang ojek",
        "Tak pernah absen meski hujan dan becek",
        "Walau kau hanya supir bajaj",
        "Hatiku senang tiap kali kau belai",
        "Percuma kau jadi pilot",
        "Makin tinggi cintamu makin melorot",
        "Apalagi kau jadi nahkoda",
        "Jarang pulang pernah kau kepincut janda",
        "Cikini ke Gondangdia",
        "Ku begini gara-gara dia",
        "Cikampek, Tasikmalaya",
        "Hati capek bila kau tak setia",
        "Jakarta ke Jayapura",
        "Jangan cinta kalau pura-pura",
        "Madura sampai Papua",
        "Jangan kira ku tak bisa mendua"
    ]}
];
